name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      balena_slugs: gh_rcooke_warwick/connector-block-test
  balena-test:
    needs: flowzone
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: 'npm install && npm run balena-test'
        env:
          BALENA_APP: gh_rcooke_warwick/connector-block-test
          BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}
          TEST_DEVICE_UUID: ${{ secrets.TEST_DEVICE_UUID }}
          GITHUB_COMMIT: ${{ github.event.pull_request.head.sha }}
  
  